src/main/java/dev/EvalMeBackApplication.java
src/main/java/dev/controller/StagiaireController.java
src/main/java/dev/metiers/StagiaireService.java
src/main/webapp/WEB-INF/views/stagiaires/creerStagiaires.jsp
src/main/webapp/WEB-INF/views/stagiaires/listerStagiaires.jsp

service stagiaire + jsp

---

src/main/java/dev/controller/ExamenController.java
src/main/java/dev/entites/Examen.java
src/main/java/dev/metiers/ExamenService.java
src/main/java/dev/repositories/examen/ExamenBaseRepositoryMemoire.java
src/main/resources/application.properties
src/main/resources/jdd/jdd-examens.xml
src/main/webapp/WEB-INF/views/examens/ajouterExamen.jsp
src/main/webapp/WEB-INF/views/examens/listerExamens.jsp
src/test/java/dev/repositories/ExamenRepositoryMemoireTest.java
src/test/java/dev/repositories/ExamenRepositoryTestConfig.java

https://examen-web-admin.herokuapp.com/examens/lister

Examen web

---

src/main/java/dev/controller/ConcoursController.java
src/main/java/dev/metiers/ConcoursService.java
src/main/java/dev/repositories/concours/ConcoursRepository.java
src/main/java/dev/repositories/concours/ConcoursRepositoryMemoire.java
src/main/resources/jdd/jdd-concours.xml
src/main/webapp/WEB-INF/views/concours/listerConcours.jsp

https://concours-web-admin.herokuapp.com/concours/lister

Josias NTUAREMBA

---

src/main/java/dev/controller/OptionQuestionController.java
src/main/java/dev/controller/QuestionController.java
src/main/java/dev/metiers/OptionQuestionService.java
src/main/java/dev/metiers/QuestionService.java
src/main/webapp/WEB-INF/views/questions/listerOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/listerQuestions.jsp

_Liste des questions :
https://question-web-admin.herokuapp.com/questions/lister
_Liste des Options pour les questions :
https://question-web-admin.herokuapp.com/questions/listerOption

Redor Mathieu : Lister Questions et OptionQuestions

---

src/main/java/dev/controller/StagiaireController.java
src/main/java/dev/entites/Stagiaire.java
src/main/java/dev/metiers/StagiaireService.java
src/main/webapp/WEB-INF/views/stagiaires/creerStagiaires.jsp

https://evalme-app-stagiaire.herokuapp.com/stagiaires/creer

service stagiaire + jsp lister

---

pom.xml
src/main/java/dev/controller/StagiaireController.java
src/main/java/dev/metiers/StagiaireService.java
src/main/java/dev/repositories/stagiaire/StagiaireRepositoryMemoire.java
src/main/webapp/WEB-INF/views/stagiaires/editerStagiaires.jsp
src/main/webapp/WEB-INF/views/stagiaires/listerStagiaires.jsp

service stagiaire update

---

src/main/java/dev/controller/OptionQuestionController.java
src/main/java/dev/controller/QuestionController.java
src/main/java/dev/entites/OptionQuestion.java
src/main/java/dev/entites/Question.java
src/main/java/dev/metiers/OptionQuestionService.java
src/main/java/dev/metiers/QuestionService.java
src/main/webapp/WEB-INF/views/questions/creerOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/creerQuestions.jsp
src/main/webapp/WEB-INF/views/questions/majOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/majQuestions.jsp

**_Création d'une option :**
https://question-web-admin.herokuapp.com/questions/creerOption
**_Création d'une question :**
https://question-web-admin.herokuapp.com/questions/creer
**_Mise à jour d'une option :**
https://question-web-admin.herokuapp.com/questions/majOption
**_Mise à jour d'une question :**
https://question-web-admin.herokuapp.com/questions/maj

Redor Mathieu

---

src/main/java/dev/controller/OptionQuestionController.java
src/main/java/dev/controller/QuestionController.java
src/main/java/dev/entites/OptionQuestion.java
src/main/java/dev/entites/Question.java
src/main/webapp/WEB-INF/views/questions/supprimerOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/supprimerQuestions.jsp

**_Suppression d'une option :**
https://question-web-admin.herokuapp.com/questions/supprimerOption
**_Suppression d'une question :**
https://question-web-admin.herokuapp.com/questions/supprimer

Redor Mathieu 

---

src/main/java/dev/controller/OptionSondageController.java
src/main/java/dev/controller/SondageController.java
src/main/java/dev/entites/OptionSondage.java
src/main/java/dev/entites/Sondage.java
src/main/java/dev/metiers/ClasseService.java
src/main/java/dev/metiers/OptionSondageService.java
src/main/java/dev/metiers/SondageService.java
src/main/java/dev/repositories/classe/ClasseRepositoryMemoire.java
src/main/java/dev/repositories/optionsondage/OptionSondageRepositoryMemoire.java
src/main/java/dev/repositories/sondage/SondageRepositoryMemoire.java
src/main/resources/jdd/jdd-OPTIONSONDAGE.xml
src/main/resources/jdd/jdd-SONDAGE.xml
src/main/webapp/WEB-INF/views/optionSondages/ajouterOptionSondage.jsp
src/main/webapp/WEB-INF/views/optionSondages/listerOptionSondages.jsp
src/main/webapp/WEB-INF/views/sondages/ajouterSondage.jsp
src/main/webapp/WEB-INF/views/sondages/listerSondages.jsp
src/test/java/dev/entites/JddSondageTest.java
src/test/java/dev/repositories/SondageRepositoryMemoireTest.java

[lister sondage 👍](https://evalme-noel.herokuapp.com/sondages/lister)
[lister optionSondage 👍](https://evalme-noel.herokuapp.com/sondages/options/lister)
[Ajouter sondage](https://evalme-noel.herokuapp.com/sondages/ajouter)
[Ajouter option sondage](https://evalme-noel.herokuapp.com/sondages/options/ajouter)

Tp3 sondage - optionSondage

---

src/main/java/dev/controller/ClasseController.java
src/main/java/dev/entites/Classe.java
src/main/java/dev/metiers/ClasseService.java
src/main/java/dev/repositories/stagiaire/StagiaireRepositoryMemoire.java
src/main/webapp/WEB-INF/views/classes/ajouterClasses.jsp

https://dta-mt-spring.herokuapp.com/classes/ajouter

Classe web admin ajouter

---

src/main/java/dev/controller/StagiaireController.java
src/main/java/dev/metiers/StagiaireService.java
src/main/webapp/WEB-INF/views/stagiaires/creerStagiaires.jsp
src/main/webapp/WEB-INF/views/stagiaires/editerStagiaires.jsp
src/main/webapp/WEB-INF/views/stagiaires/listerStagiaires.jsp
src/main/webapp/WEB-INF/views/stagiaires/supprimerStagiaires.jsp

service stagiaire delete

---

src/main/java/dev/controller/QuizzController.java
src/main/java/dev/entites/Quizz.java
src/main/java/dev/metiers/QuizzService.java
src/main/java/dev/repositories/BaseRepositoryMemoire.java
src/main/webapp/WEB-INF/views/quizzes/listerQuizz.jsp

https://evalme-ctorres.herokuapp.com/quizzes/lister

Quizz - Editer

---

src/main/java/dev/controller/QuizzController.java
src/main/webapp/WEB-INF/views/quizzes/listerQuizz.jsp

https://evalme-ctorres.herokuapp.com/quizzes/lister

Quizz - Supprimer

---

src/main/java/dev/controller/ClasseController.java
src/main/java/dev/metiers/ClasseService.java
src/main/java/dev/repositories/classe/ClasseRepositoryMemoire.java
src/main/resources/bdd/data.sql
src/main/webapp/WEB-INF/views/classes/listerClasses.jsp
src/main/webapp/WEB-INF/views/classes/majClasse.jsp
src/main/webapp/WEB-INF/views/classes/supprimerClasses.jsp
src/main/webapp/WEB-INF/views/structure.css

https://dta-mt-spring.herokuapp.com/classes/lister

CRUD Complet opérationel

---

src/main/java/dev/repositories/stagiaire/StagiaireRepositoryJdbc.java
src/main/java/dev/repositories/stagiaire/StagiaireRepositoryMemoire.java
src/main/java/dev/repositories/stagiaire/mapper/StagiaireMapper.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/test/java/dev/repositories/stagiaire/StagiaireRepositoryJdbcTest.java
src/test/java/dev/repositories/stagiaire/StagiaireRepositoryMemoireTest.java

Stagiaire jdbc

---

src/main/java/dev/entites/OptionQuestion.java
src/main/java/dev/repositories/duel/DuelDataJpaRepository.java
src/main/java/dev/repositories/duel/DuelRepositoryDataJpa.java
src/main/java/dev/repositories/duel/DuelRepositoryJdbc.java
src/test/java/dev/config/DataJpaTestConfig.java
src/test/java/dev/repositories/duel/DuelRepositoryDataJpaTest.java

https://evalme-back.herokuapp.com/duels/lister

CRUD Data JPA Duel

---

src/main/java/dev/repositories/duel/DuelRepositoryJpa.java
src/main/java/dev/repositories/stagiaire/StagiaireDataJpaRepo.java
src/main/java/dev/repositories/stagiaire/StagiaireRepositoryDataJpa.java
src/main/java/dev/repositories/stagiaire/StagiaireRepositoryJpa.java
src/main/resources/data.sql
src/main/resources/schema-mysql.sql
src/main/resources/schema-postgres.sql
src/test/java/dev/config/DataJpaTestConfig.java
src/test/java/dev/repositories/stagiaire/StagiaireRepositoryDataJpaTest.java

Stagiaire spring data

---

src/main/java/dev/controller/ClasseController.java
src/main/java/dev/entites/Classe.java
src/main/java/dev/repositories/classe/ClasseDataJpaRepo.java
src/main/java/dev/repositories/classe/ClasseRepositoryDataJpa.java
src/main/java/dev/repositories/classe/ClasseRepositoryJPA.java
src/main/java/dev/repositories/classe/ClasseRepositoryJdbc.java
src/main/java/dev/repositories/classe/ClasseRepositoryMemoire.java
src/main/java/dev/repositories/classe/mapper/ClasseMapper.java
src/main/resources/data.sql
src/main/webapp/WEB-INF/views/classes/listerClasses.jsp
src/main/webapp/WEB-INF/views/classes/structures.css
src/main/webapp/WEB-INF/views/classes/supprimerClasses.jsp
src/test/java/dev/repositories/classe/ClasseRepositoryDataJpaTest.java
src/test/java/dev/repositories/classe/ClasseRepositoryJPATest.java
src/test/java/dev/repositories/classe/ClasseRepositoryJdbcTest.java
src/test/java/dev/repositories/classe/ClasseRepositoryMemoireTest.java

https://dta-mt-spring.herokuapp.com/classes/lister

Classe jpav3

---

pom.xml
src/main/java/dev/entites/OptionQuestion.java
src/main/java/dev/entites/Question.java
src/main/java/dev/repositories/question/OptionQuestionAppConfig.java
src/main/java/dev/repositories/question/OptionQuestionDataJpaRepo.java
src/main/java/dev/repositories/question/OptionQuestionRepositoryDataJpa.java
src/main/java/dev/repositories/question/OptionQuestionRepositoryJpa.java
src/main/java/dev/repositories/question/OptionQuestionRepositoryMemoire.java
src/main/java/dev/repositories/question/QuestionAppConfig.java
src/main/java/dev/repositories/question/QuestionDataJpaRepo.java
src/main/java/dev/repositories/question/QuestionRepositoryDataJpa.java
src/main/java/dev/repositories/question/QuestionRepositoryMemoire.java
src/main/resources/data.sql
src/main/resources/schema-mysql.sql
src/main/resources/schema-postgres.sql
src/main/webapp/WEB-INF/views/questions/creerOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/creerQuestions.jsp
src/main/webapp/WEB-INF/views/questions/majOptionQuestions.jsp
src/main/webapp/WEB-INF/views/questions/majQuestions.jsp
src/test/java/dev/config/DataJpaTestConfig.java
src/test/java/dev/repositories/question/OptionQuestionRepositoryDataJpaTest.java
src/test/java/dev/repositories/question/OptionQuestionRepositoryJpaTest.java
src/test/java/dev/repositories/question/OptionQuestionRepositoryMemoireTest.java
src/test/java/dev/repositories/question/QuestionRepositoryDataJpaTest.java
src/test/java/dev/repositories/question/QuestionRepositoryMemoireTest.java

**_Lister Questions :** 
https://question-web-admin.herokuapp.com/questions/lister

Redor Mathieu - Data-JPA

---

src/main/java/dev/controller/api/viewModels/classe/BaseVm.java
src/main/java/dev/controller/api/viewModels/classe/ClasseApiController.java
src/main/java/dev/controller/api/viewModels/classe/ClasseVmAjouter.java
src/main/java/dev/controller/api/viewModels/classe/ClasseVmDetail.java
src/main/java/dev/controller/api/viewModels/classe/ClasseVmLister.java
src/main/java/dev/controller/api/viewModels/classe/StagiaireVmDetail.java
src/main/java/dev/controller/api/viewModels/examen/ClasseVm.java

https://dta-mt-spring.herokuapp.com/api/classes

Lister + lister détail API

---

src/main/java/dev/controller/api/ExamenApiController.java
src/main/java/dev/controller/api/sondage/viewModels/OptionSondageLibelleDescVM.java
src/main/java/dev/controller/api/sondage/viewModels/SondageCreateResponseVM.java
src/main/java/dev/controller/api/sondage/viewModels/SondageCreateVM.java
src/main/java/dev/controller/api/viewModels/examen/ExamenVm.java
src/main/java/dev/controller/api/viewModels/examen/ExamenVmUtil.java

https://evalme-noel.herokuapp.com/api/examens/1

api list des exams pour un stagiaire

---

src/main/java/dev/controller/api/sondage/ListerSondageApiController.java
src/main/java/dev/controller/api/sondage/SondageBuilder.java
src/main/java/dev/controller/api/stagiaire/StagiaireApiController.java

https://dta-mt-spring.herokuapp.com/api/stagiaires/1

api sondage par id stagiaire et stagiaire par id

---

src/main/java/dev/EvalMeBackApplication.java
src/main/java/dev/controller/api/stagiaire/StagiaireApiController.java
src/main/java/dev/controller/api/stagiaire/StagiaireVm.java

https://dta-mt-spring.herokuapp.com/api/stagiaires

ajout api updateStagiaire

---

src/main/java/dev/controller/api/resultatDuel/AdversaireVm.java
src/main/java/dev/controller/api/resultatDuel/ResultatDuelApiController.java
src/main/java/dev/controller/api/resultatDuel/ResultatDuelVm.java

https://evalme-app-stagiaire.herokuapp.com/api/resultats-duels

creation web api en dure pour resultats-duels

---

src/main/java/dev/EvalMeBackApplication.java
src/main/java/dev/controller/api/concours/PassageConcoursController.java
src/main/java/dev/controller/api/viewModels/passageConcours/ResultatConcoursVm.java
src/main/java/dev/controller/api/viewModels/passageConcours/ScoreConcoursVm.java
src/main/java/dev/entites/PassageConcours.java
src/main/java/dev/metiers/PassageConcoursService.java
src/main/java/dev/repositories/concours/PassageConcoursRepository.java
src/main/resources/application.properties
src/main/resources/data.sql
src/main/resources/schema-mysql.sql
src/main/resources/schema-postgres.sql
src/test/java/dev/repositories/question/OptionQuestionRepositoryDataJpaTest.java
src/test/java/dev/repositories/question/OptionQuestionRepositoryJpaTest.java

commencer un concours : cliquer sur bouton participer
Donner un score au passage : `PUT -> http://localhost:8080/api/passage_concours/resultat`
Récupérer le résultat de tous les concours d'un stagiaire : `http://localhost:8080/api/passage_concours/resultat?id_stagiaire=xx`

Debut api et JS passage concours
